name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint -- --fix

    - name: Build project
      run: npm run build

    - name: Archive build output
      run: zip -r web.zip ./build

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-build
        path: web.zip
